### ISSUE TITLE
Estudar desenvolvimento web.

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#1]

**Comment by GuilhermeFFe** [comment]
https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/?hl=pt-br

**Comment by GuilhermeFFe** [comment]
https://medium.com/tableless/como-criar-seu-primeiro-progressive-web-app-do-zero-a7e6ca5fb21e

**Comment by GuilhermeFFe** [comment]
Alguns tutoriais úteis:
- [Como criar seu primeiro Progressive Web App do Zero - Medium](https://medium.com/tableless/como-criar-seu-primeiro-progressive-web-app-do-zero-a7e6ca5fb21e)
- [Seu primeiro Progressive Web App - Developers Google](https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/?hl=pt-br)

**Comment by GuilhermeFFe** [comment]
Outro endereço interessante: https://serviceworkies.com/

**Comment by GuilhermeFFe** [comment]
[Cursos RocketSeat](https://rocketseat.com.br/starter)

**Comment by GuilhermeFFe** [comment]
[Progressive web apps - Google](https://developers.google.com/web/progressive-web-apps/)

**Comment by GuilhermeFFe** [comment]
[Tutorial de PWAs no YouTube](https://www.youtube.com/watch?v=4XT23X0Fjfk&list=PL4cUxeGkcC9gTxqJBcDmoi5Q2pzDusSL7&index=1)

**Comment by EduardaPS** [comment]
`<html>
    <head>
        <title>teste</title>
    </head>
    <body>
        <script>
            //codigo pois se for nessesario acessar algo ja estara renderizado
        </script>
    </body>
</html>`

**Comment by EduardaPS** [comment]
```
<html>
    <head>
        <title>teste</title>
    </head>
    <body>
        <script>
            // não é tipada, é uma tipagem dinamica
            //variavel -> var
            let nome = "Maria"
            nome = 2;//sim isso funciona que agonia
            //tipos de variaveis
            nome = "Maria" //não precisou do var pois já estava declarado
            let idade = 23;
            let peso = 54.5;
            let humano = true;
            let alunos = ['joao', 'maria','lucas'];
            let aluno = {
                nome : 'diego',
                idade : 23,
                peso : 34
            };
            // mostrando no console 
            console.log(alunos[1]);
            console.log(aluno.peso)

            //pelo visto não é bom usar var e sim let
        </script>
    </body>
</html>
```

**Comment by GuilhermeFFe** [comment]
Evitaremos o uso de var devido ao não bloqueio de escopo.
https://dev.to/johnwolfe820/should-you-never-truly-use-var-bdi

**Comment by EduardaPS** [comment]
operações
```
<html>
    <head>
        <title>teste</title>
    </head>
    <body>
        <script>
           let x = 1, y = 3;
           let resultado = x + y;
           let modulo = x % y; //resto da divisão

           x += 3; //incrementando
           // funciona qualquer outro operador

           x = "1";
           let result2 = x + y; // concatena string
           console.log(x,y,resultado,result2);
        </script>
    </body>
</html>
```

**Comment by GuilhermeFFe** [comment]
**Como importar um arquivo javascript em um HTML**

index.html:
```html
<html>
	<head>
	</head>
	<body>
		<script src="main.js"></script>
	</body>
</html>
```

main.js:
`console.log('Hello world!');`

**Comment by EduardaPS** [comment]
outras funções
```html
<html>
    <head>
        <title>teste</title>
    </head>
    <body>
        <script>
           function retorna_sexo(sexo){
               if(sexo === 'M'){
                //se colocar === ele checa o tipo da variavel tambem
                //== são apenas os valores
                   return 'Masculino';
               }else return 'Feminino';
               switch(sexo){
                   case 'M':
                   return 'Masculino';
                   default:
                   return 'Feminino';
               }
               let masculino = (sexo === 'M');

               return (sexo === 'M') ? 'Masculino' : 'Feminino';
               // simplificando o if

               // && e
               // || ou
               // !== diferente mas mesmo tipo
               // != diferente
           }

           for(let i=0; i<=10; i++){   
           }
           let j = 12133432535;
           while(j > 50){
               j /= 5;
           }
           let resultado = retorna_sexo('M');
           
           setInterval(retorna_sexo,1000);
         // executa varias vezes 
         setTimeout(retorna_sexo,1000);
         //delay antes de executar
        </script>
    </body>
</html>
```

**Comment by EduardaPS** [comment]
[Como criar uma classe em javascript](https://blog.schoolofnet.com/tudo-o-que-voce-precisa-saber-sobre-classes-no-javascript/)

**Comment by GuilhermeFFe** [comment]
**Progressive Web Apps:**

- Ideia principal ([Matheus Lima - Medium](https://medium.com/tableless/introdu%C3%A7%C3%A3o-aos-progressive-web-apps-ad47ba24cddb)):
    - Os Progressive Web Apps são um conjunto de técnicas para desenvolver aplicações web, adicionando progressivamente funcionalidades que antes só eram possíveis em apps nativos.

**Comment by GuilhermeFFe** [comment]
A estrutura dos PWAs consistem no uso de alguns arquivos, dentre eles:

**manifest.json**
O arquvio _manifest.json_ é como um arquivo de configuração em formato json, que serve para tornar a aplicação web instalável no _smartphone_. Abaixo, o exemplo (modificado para contexto) dado pelo [artigo/tutorial](https://medium.com/tableless/como-criar-seu-primeiro-progressive-web-app-do-zero-a7e6ca5fb21e) do Matheus Lima na Medium:
```json
{
  "name": "Simple Hello",
  "short_name": "SimpleHello",
  "theme_color": "#000000",
  "background_color": "#000000",
  "display": "standalone",
  "start_url": "/",
  "icons": [
    {
      "src": "images/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    }
  ]
}
```

A ideia é, com esse arquivo, permitir com que a tela do telefone abra o aplicativo web de maneira similar a um aplicativo instalado nativamente, feito em java, flutter ou outras linguagens.

**Comment by GuilhermeFFe** [comment]
**Service Workers**

- Um Service Worker é um script que seu navegador executa em segundo plano, separado da página da Web, possibilitando recursos que não precisam de uma página da Web ou de interação do usuário. [Matheus Lima - Medium](https://medium.com/tableless/como-criar-seu-primeiro-progressive-web-app-do-zero-a7e6ca5fb21e)

Não entrarei em detalhes sobre Service Workers, pois vi sobre o uso da aplicação offline.

**Comment by GuilhermeFFe** [comment]
**Conclusão**

Com estes pontos supracitados, pode-se desenvolver uma aplicação web de maneira comum (JavaScript, HTML, como já estamos acostumados) e _voilà_, temos um PWA. Agora estamos prontos para o desenvolvimento do aplicativo.
