### ISSUE TITLE
Design da tela de cadastro (autenticação).

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#10]

**Comment by EduardaPS** [comment]
A tela de cadastro principal consiste basicamente de um formulário contendo nome, sobrenome, CPF, email, confirmação de email, senha e confirmação de senha. Após isso, o usuário poderá cadastrar as informações na tela de cadastro de informações (ver #11 )

**Comment by EduardaPS** [comment]
### Imagens

Também há a mudança do fato de que o usuário, quando não autenticado, não pode ver as funcionalidades de criação e exibição de QRCodes, isto está mostrado na barra de navegação na parte superior da tela.

![Tela cadastro (autenticação) - grande](https://user-images.githubusercontent.com/42206193/65001248-1db3f280-d8c5-11e9-9326-328893f1eddb.jpg)
![Tela cadastro (autenticação) - pequeno](https://user-images.githubusercontent.com/42206193/65001249-1e4c8900-d8c5-11e9-81bf-25c77d46821a.jpg)
