### ISSUE TITLE
Design da tela de cadastro (informações).

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#11]

**Comment by EduardaPS** [comment]
### Não haverá uma tela para cadastro de informações separada!

A tela de exeibição de informações será a mesma utilizada para a modificação e cadastro de informações do indivíduo. Ver #12

**Comment by EduardaPS** [comment]
O indivíduo, ao se logar no app, poderá entrar na tela de exibição de informações, onde todos os campos estarão vazios. Caso ele já tenha cadastrado alguma, estes campos de _text input_ estarão preenchidos com estas informações.
