### ISSUE TITLE
Design da tela de exibição de informações.

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#12]

**Comment by EduardaPS** [comment]
A tela de exibição de informações será a mesma utilizada para a edição das mesmas. Nas informações já possuídas, os campos de texto estarão preenchidos previamente.

**Comment by EduardaPS** [comment]
### Imagens das telas de informações
A primeira é a imagem do design da tela de informações vista em um computador com o monitor grande, a próxima é em um celular ou em um computador com um monitor mais fraco. Nesta, o menu na parte superior esquerda se expande para mostrar os mesmos links mostrados na barra de navegação da tela grande.

![Tela informacoes - grande](https://user-images.githubusercontent.com/42206193/64928646-9f3a5080-d7f1-11e9-9d2a-5933ba96eef2.jpg)
![Tela informacoes - pequeno](https://user-images.githubusercontent.com/42206193/64928647-9fd2e700-d7f1-11e9-938d-737b90d9436a.jpg)

**Comment by EduardaPS** [comment]
Ao fazer o designer das outras telas foi encontrado um padrão mais adequado 

![Tela informacoes - grande](https://user-images.githubusercontent.com/42206193/65165280-da689980-da14-11e9-8395-b5529c763845.jpg)
![Tela informacoes - pequeno](https://user-images.githubusercontent.com/42206193/65165287-dd638a00-da14-11e9-8b46-45e1949818c7.jpg)
