### ISSUE TITLE
Design da tela principal.

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#20]

**Comment by EduardaPS** [comment]
A tela principal mostrará um texto que explica os objetivos da aplicação.
O texto poderá sofrer alterações posteriormente. 
 
![telaPrincipal](https://user-images.githubusercontent.com/42206193/66007902-9cdf2400-e48a-11e9-8a45-fc4074cc1c36.png)
