### ISSUE TITLE
Design da tela de criar um QR Code a partir de um modelo.

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#22]

**Comment by EduardaPS** [comment]
A tela será um modal. Onde clicar em um botão será redirecionada a tela de criar QRcode com os check box já selecionados.  
![qrcodePadao](https://user-images.githubusercontent.com/42206193/66067819-c3509e00-e522-11e9-9778-ee477aa8bae2.png)
