### ISSUE TITLE
Definir tipo de criptografia que será utilizada entre cliente (PWA/app) e servidor (aplicação Web).

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#3]

**Comment by GuilhermeFFe** [comment]
Apenas para lembrar do que foi dito no encontro anterior com o professor:

**PWAs utilizam por padrão HTTPS!**

Mas, por estarmos lidando com dados pessoais que podem ser considerados sensíveis (endereços, por exemplo), cabe o uso de uma camada a mais de segurança, mesmo que isso afete performance.

**Comment by gabrielturnes** [comment]
Para a segurança dos dados do usuário, iremos utilizar a criptografia do tipo **AES256**.
Considerado um dos tipos de criptografia mais seguro atualmente, AES256 utiliza 256 bits e é o algoritmo padrão utilizado no governo dos EUA, imune a quase todos os ataques, exceto aos de força bruta.
