### ISSUE TITLE
Máscaras em campos (CPF, RG, etc)

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#52]

**Comment by gabrielturnes** [comment]
Através de um plugin chamado JMask agora alguns campos possuem máscaras para formatação dos dados que estão sendo enviados para nosso banco de dados. Além da biblioteca, também usamos algumas funcionalidades do HTML5 para que possamos ter mais controle na hora do preenchimento dos formulários.
