### ISSUE TITLE
Modelagem do banco de dados.

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#8]

**Comment by gabrielturnes** [comment]
Para o banco de dados, pensamos em ter 4 collections: user, qrcode, logEdit, accessClient.

`user{
_id, nome, password, sobrenome, cpf, tipo, demais dados... 
}
`
O campo "tipo" seria para diferenciar uma pessoa física de uma pessoa jurídica.

`qrcode{_id, _idUser, permissoes[ ], createdAt, dateValid}`
O campo "permissões" seria um vetor que conteria os campos que o usuário disponibilizaria. 
O campo "dateValid" seria para caso o usuário queira que aquele QRCode tenha uma data de validade.

`logEdit{_id, _idUser, campos[ ], date}`
O campo "campos" seria um vetor para armazenar os campos que o usuário editou naquela data.

`accessCliente{_id, _idCliente, _idUser, lastAccess}`
O campo "lastAccess" guardaria a última vez que um _User_ captou os dados de outro _User_.
