### ISSUE TITLE
Design da tela de login.

### ISSUE THREAD

**Issue by GuilhermeFFe** [PI2-Passig-Turnes-Fleiger/simple-hello#9]

**Comment by EduardaPS** [comment]
A tela de login será um modal do Bootstrap. Uma espécie de popup na tela, que aparece quando o usuário clica em "fazer login".

**Comment by EduardaPS** [comment]
![Captura de tela de 2019-09-17 10-46-02](https://user-images.githubusercontent.com/42206193/65047985-c0a65400-d939-11e9-8b87-90366253e89b.png)

**Comment by GuilhermeFFe** [comment]
deixar um texto sublinhado de 'esqueci minha senha'
